name: AWS Actions
jobs:
  IAM:
    name: IAM Service
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEY }}
          aws-region: us-east-1
      - name: Print env region
        run: echo ${{ env.AWS_REGION }}
      - name: List IAM Users
        run: aws iam list-users
          
          
          
        
        

      
