name: challange-2
on: push
env: 
  ARTIFACT_NAME: README.md
jobs: 
  job-1:
    name: Challange Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v1
      - name: upload_file
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ReadMe
          path: ./${{ env.ARTIFACT_NAME }}
  job-2:
    name: Download and Test Artifact
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: download_file
        uses: actions/download-artifact@v1.0.0
        with: 
          name: ReadMe
      - name: test_file
        run: ls -l

