name: Challange-1
on: push
jobs:
  Job-1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  Job-2
    name: Second Job
    runs-on: window-latest
    steps:
      - name: print date
        run: echo  %date%-%time%
