name: Challange-1
on: push
jobs:
  Job-1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  Job-2:
    name: Second Job
    runs-on: window-latest
    steps:
      - name: print date
        run: Get-Date
  Job-3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: print date
        run: date
  Job-4:
    name: Forth Job
    needs: [Job-1, Job-2, Job-3]
    runs-on: ubuntu-latest
    steps:
      - name: final command
        run: echo "This is last job of this workflow."
              
