name: exe-1
on: push
jobs:
  Job-1:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort
  Job-2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name: Step 2
        run: "Get-ChildItem Env: | Sort-Object Name"