name: exe-1
on: pull_request
jobs:
  Job-1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: env | sort
  Job-2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v2
      - name: Step 2
        run: "Get-ChildItem Env: | Sort-Object Name"
  Job-3:
    name: Third Job
    runs-on: ubuntu-latest
    needs: [Job-1, Job-2]
    steps:
      - name: Only one step
        run: echo "Hallo, wie gest's?"       
